version: "3"

services:
  redis:
    image: redis
    command: redis-server --requirepass password
    ports:
      - "6379:6379"

  app:
    container_name: broker-service
    build: .
    volumes:
      - .:/go/src/
    depends_on:
      - redis
    environment:
      HOST_ID: B01
      GOPOOL_SIZE: 124
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_DATABASE: chat_db
      DB_SCHEMA: chat_db
      DB_USER: salesapi
      DB_PASSWORD: password
      REDIS_HOST: host.docker.internal:6379
      REDIS_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9094
      KAFKA_CLIENT_ID: BROKER_SERVICE
      KAFKA_GROUP_ID: BROKER_SERVICE
      KAFKA_SERVERS_TOPIC: SERVERS
      KAFKA_USERS_TOPIC: USERS
      KAFKA_USERS_PRESENCE_TOPIC: USERS_PRESENCE
      KAFKA_NEW_MESSAGES_TOPIC: NEW_MESSAGES
      KAFKA_OFF_MESSAGES_TOPIC: OFF_MESSAGES
      KAFKA_ERRORS_TOPIC: ERRORS
      KAFKA_GROUP_EVENT_TOPIC: GROUP_EVENTS
      KAFKA_HOST_TOPIC: MESSAGES

    extra_hosts:
      - "host.docker.internal:172.17.0.1"