version: "3"

services:
  redis:
    image: redis
    command: redis-server --requirepass password
    ports:
      - "6379:6379"

  app:
    container_name: broker-service
    build: .
    volumes:
      - .:/go/src/
    depends_on:
      - redis
    environment:
      HOST_ID: BROKER01
      GOPOOL_SIZE: 128
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_SCHEMA: chat_db
      DB_USER: salesapi
      DB_PASSWORD: password
      REDIS_HOST: localhost:6379
      REDIS_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: localhost:9094
      KAFKA_CLIENT_ID: B01_BROKER_SERVICE
      KAFKA_GROUP_ID: BROKER_SERVICE
      KAFKA_USERS_TOPIC: USERS
      KAFKA_USERS_PRESENCE_TOPIC: USERS_PRESENCE
      KAFKA_NEW_MESSAGES_TOPIC: NEW_MESSAGES
      KAFKA_OFF_MESSAGES_TOPIC: OFF_MESSAGES
      KAFKA_GROUP_EVENT_TOPIC: GROUP_EVENTS
      KAFKA_CONTACT_EVENT_TOPIC: CONTACT_EVENTS
      KAFKA_HOST_TOPIC: MESSAGES
      KAFKA_EVENTS_TOPIC: EVENTS