version: "3.8"

services: 
    postgres:
        image: postgres:14.5
        restart: 'no'
        container_name: postgres_db
        ports: 
            - 5432:5432
        volumes: 
            - pg-data:/var/lib/postgresql/data
        environment: 
            POSTGRES_DB: 'postgres'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres-password'

volumes:
    pg-data: