version: "3"

services:
  app:
    container_name: file-service
    build: .
    ports:
      - "8083:8083"
    volumes:
      - .:/go/src
    environment:
      HOST_ID: FILE01
      SERVER_PORT: 8083
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_SCHEMA: chat_db
      DB_USER: salesapi
      DB_PASSWORD: password
      MAX_UPLOAD_SIZE: 10
      KAFKA_BOOTSTRAP_SERVERS: localhost:9094
      KAFKA_CLIENT_ID: FILE_SERVICE
      KAFKA_EVENTS_TOPIC: EVENTS