version: "3"

services:
  app:
    container_name: file-service
    build: .
    ports:
      - "8083:8083"
    volumes:
      - .:/go/src
    environment:
      HOST_ID: FILE01
      SERVER_PORT: 8083
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_SCHEMA: chat_db
      DB_USER: salesapi
      DB_PASSWORD: password
      MAX_UPLOAD_SIZE: 10
      METRICS_SEND_INTERVAL: 60
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9094
      KAFKA_CLIENT_ID: FILE_SERVICE
      KAFKA_EVENTS_TOPIC: EVENTS
      KAFKA_METRICS_TOPIC: METRICS
    extra_hosts:
      - "host.docker.internal:172.17.0.1"