// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/tsmweb/chat-service/api"
	"github.com/tsmweb/chat-service/common/concurrent"
	"github.com/tsmweb/chat-service/common/connutil"
	"github.com/tsmweb/chat-service/common/epoll"
	"github.com/tsmweb/chat-service/common/setting"
	"github.com/tsmweb/chat-service/core"
	"github.com/tsmweb/chat-service/infrastructure/db"
	"github.com/tsmweb/easygo/netpoll"
	"github.com/tsmweb/go-helper-api/auth"
	"github.com/tsmweb/go-helper-api/middleware"
)

// Injectors from wire.go:

func InitChat(localhost string, executor concurrent.ExecutorService) (*api.Router, error) {
	jwt := ProviderJWT()
	auth := middleware.NewAuth(jwt)
	errorDispatcher := core.NewErrorDispatcher()
	config := ProviderPollerConfig(executor, errorDispatcher)
	poller, err := netpoll.New(config)
	if err != nil {
		return nil, err
	}
	ePoll := epoll.NewEPoll(poller)
	reader := ProviderConnReader()
	writer := ProviderConnWriter()
	repository := core.NewMemoryRepository()
	presenceDispatcher := core.NewPresenceDispatcher()
	userStatusHandler := core.NewUserStatusHandler(repository, presenceDispatcher)
	offlineMessageDispatcher := core.NewOfflineMessageDispatcher()
	groupMessageDispatcher := core.NewGroupMessageDispatcher()
	messageHandler := core.NewMessageHandler(repository, offlineMessageDispatcher, groupMessageDispatcher)
	chat := core.NewChat(ePoll, executor, localhost, reader, writer, userStatusHandler, messageHandler, errorDispatcher)
	controller := api.NewController(jwt, chat)
	router := api.NewRouter(auth, controller)
	return router, nil
}

// wire.go:

func ProviderConnReader() connutil.Reader {
	return connutil.FuncReader(connutil.ReaderWS)
}

func ProviderConnWriter() connutil.Writer {
	return connutil.FuncWriter(connutil.WriterWS)
}

// Data Base
var databaseInstance db.Database

func ProviderDataBase() db.Database {
	if databaseInstance == nil {
		databaseInstance = db.NewPostgresDatabase()
	}

	return databaseInstance
}

// Authentication MockJWT
var jwtInstance auth.JWT

func ProviderJWT() auth.JWT {
	if jwtInstance == nil {
		jwtInstance = auth.NewJWT(setting.PathPrivateKey(), setting.PathPublicKey())
	}

	return jwtInstance
}

// Poller OnWaitError will be called from goroutine, waiting for events.
func ProviderPollerConfig(executor concurrent.ExecutorService, dispatcher *core.ErrorDispatcher) *netpoll.Config {
	return &netpoll.Config{
		OnWaitError: func(err error) {
			executor.Schedule(func(ctx context.Context) {
				dispatcher.Send(err)
			})
		},
	}
}
