FROM golang:1.18

WORKDIR /go/src
ENV PATH="/go/bin:${PATH}"

RUN apt-get update && \
    apt-get install build-essential -y

COPY . .
RUN GOOS=linux go build -ldflags="-s -w" -o chat cmd/chat/main.go cmd/chat/di.go
ENTRYPOINT ["./chat"]