version: "3"

services:
  app:
    container_name: chat-service
    build: .
    ports:
      - "8080:8080"
      - "6060:6060"
    volumes:
      - .:/go/src/
    environment:
      HOST_ID: H01
      SERVER_PORT: 8080
      PPROF_PORT: 6060
      GOPOOL_SIZE: 128
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9094
      KAFKA_CLIENT_ID: CHAT_SERVICE
      KAFKA_GROUP_ID: CHAT_SERVICE
      KAFKA_SERVERS_TOPIC: SERVERS
      KAFKA_USERS_TOPIC: USERS
      KAFKA_USERS_PRESENCE_TOPIC: USERS_PRESENCE
      KAFKA_NEW_MESSAGES_TOPIC: NEW_MESSAGES
      KAFKA_OFF_MESSAGES_TOPIC: OFF_MESSAGES
      KAFKA_ERRORS_TOPIC: ERRORS
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
