version: "3"

services:
  app:
    container_name: auth-service
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/go/src/
    environment:
      HOST_ID: AUTH01
      SERVER_PORT: 8081
      EXPIRE_TOKEN: 24
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_SCHEMA: chat_db
      DB_USER: salesapi
      DB_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: localhost:9094
      KAFKA_CLIENT_ID: AUTH_SERVICE
      KAFKA_EVENTS_TOPIC: EVENTS

