version: "3"

services:
  app:
    container_name: auth-service
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/go/src/
    environment:
      SERVER_PORT: 8081
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_DATABASE: chat_db
      DB_SCHEMA: chat_db
      DB_USER: salesapi
      DB_PASSWORD: password
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

