version: "3"

services:
  app:
    container_name: user-service
    build: .
    ports:
      - "8082:8082"
    volumes:
      - .:/go/src/
    environment:
      HOST_ID: USER01
      SERVER_PORT: 8082
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_SCHEMA: chat_db
      DB_USER: salesapi
      DB_PASSWORD: password
      KAFKA_BOOTSTRAP_SERVERS: localhost:9094
      KAFKA_CLIENT_ID: USER_SERVICE
      KAFKA_GROUP_EVENT_TOPIC: GROUP_EVENTS
      KAFKA_CONTACT_EVENT_TOPIC: CONTACT_EVENTS
      KAFKA_EVENTS_TOPIC: EVENTS
