FROM golang:1.19

WORKDIR /go/src
ENV PATH="/go/bin:${PATH}"

RUN apt-get update && \
    apt-get install build-essential -y

COPY . .
RUN GOOS=linux go build -ldflags="-s -w" -o user cmd/user/main.go cmd/user/di.go
ENTRYPOINT ["./user"]